version: '3.5'
services: 
    
    neo4j-test-playground: 
      image: neo4j:latest
      ports:
        - 7474:7474
        - 7473:7473
        - 7687:7687
      volumes: 
        - ./data/:/data
        - ./logs/:/logs
      container_name: 'neo4j-test-playground'
      networks: 
        - neo4jnetwork
networks: 
    neo4jnetwork:
        name: neo4jnetwork