version: '3.5'

services: 
    zookeper:
        image: zookeeper
        restart: always
        ports: 
            - 2181:2181
        volumes: 
        environment: 
            - ALLOW_ANONYMOUS_LOGIN=yes